AWSTemplateFormatVersion: '2010-09-09'
Description: 'ESG Navigator - Application Load Balancer'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: Environment name for resource tagging

  CertificateArn:
    Type: String
    Description: ARN of ACM certificate for HTTPS

  DomainName:
    Type: String
    Default: esgnavigator.ai
    Description: Primary domain name

Resources:
  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${EnvironmentName}-esg-alb'
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - Fn::ImportValue: !Sub '${EnvironmentName}-ALBSecurityGroupId'
      Subnets:
        - Fn::ImportValue: !Sub '${EnvironmentName}-PublicSubnet1'
        - Fn::ImportValue: !Sub '${EnvironmentName}-PublicSubnet2'
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
        - Key: deletion_protection.enabled
          Value: 'true'
        - Key: routing.http2.enabled
          Value: 'true'
        - Key: access_logs.s3.enabled
          Value: 'false'
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-esg-alb'
        - Key: Environment
          Value: !Ref EnvironmentName

  # HTTP Listener (redirect to HTTPS)
  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            Host: '#{host}'
            Path: '/#{path}'
            Query: '#{query}'
            StatusCode: HTTP_301

  # HTTPS Listener
  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebTargetGroup

  # Target Group for Web (Next.js frontend)
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${EnvironmentName}-web-tg'
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VpcId'
      Port: 3000
      Protocol: HTTP
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-399
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
        - Key: stickiness.enabled
          Value: 'false'
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-web-tg'

  # Target Group for API
  APITargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${EnvironmentName}-api-tg'
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VpcId'
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
        - Key: stickiness.enabled
          Value: 'false'
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-api-tg'

  # Listener Rule for API routes
  APIListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - '/api/*'
      Actions:
        - Type: forward
          TargetGroupArn: !Ref APITargetGroup

  # Listener Rule for Health Check
  HealthCheckListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 5
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - '/health'
      Actions:
        - Type: forward
          TargetGroupArn: !Ref APITargetGroup

  # Listener Rule for WebSocket
  WebSocketListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 15
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - '/realtime'
              - '/realtime/*'
      Actions:
        - Type: forward
          TargetGroupArn: !Ref APITargetGroup

Outputs:
  LoadBalancerArn:
    Description: Application Load Balancer ARN
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub '${EnvironmentName}-ALBArn'

  LoadBalancerDNSName:
    Description: Application Load Balancer DNS Name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub '${EnvironmentName}-ALBDNSName'

  LoadBalancerHostedZoneId:
    Description: Application Load Balancer Hosted Zone ID
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Sub '${EnvironmentName}-ALBHostedZoneId'

  HTTPSListenerArn:
    Description: HTTPS Listener ARN
    Value: !Ref HTTPSListener
    Export:
      Name: !Sub '${EnvironmentName}-HTTPSListenerArn'

  WebTargetGroupArn:
    Description: Web Target Group ARN
    Value: !Ref WebTargetGroup
    Export:
      Name: !Sub '${EnvironmentName}-WebTargetGroupArn'

  APITargetGroupArn:
    Description: API Target Group ARN
    Value: !Ref APITargetGroup
    Export:
      Name: !Sub '${EnvironmentName}-APITargetGroupArn'
